name: Download and Install Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile

    - name: Restart frontend service
      run: sudo systemctl restart frontend.service

